/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'
import { Route as WatchAnimeIdEpisodeIdRouteImport } from './routes/watch.$animeId.$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchAnimeIdEpisodeIdRoute = WatchAnimeIdEpisodeIdRouteImport.update({
  id: '/watch/$animeId/$episodeId',
  path: '/watch/$animeId/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/watch/$animeId/$episodeId': typeof WatchAnimeIdEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/watch/$animeId/$episodeId': typeof WatchAnimeIdEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/watch/$animeId/$episodeId': typeof WatchAnimeIdEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anime/$animeId' | '/watch/$animeId/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anime/$animeId' | '/watch/$animeId/$episodeId'
  id: '__root__' | '/' | '/anime/$animeId' | '/watch/$animeId/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  WatchAnimeIdEpisodeIdRoute: typeof WatchAnimeIdEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$animeId/$episodeId': {
      id: '/watch/$animeId/$episodeId'
      path: '/watch/$animeId/$episodeId'
      fullPath: '/watch/$animeId/$episodeId'
      preLoaderRoute: typeof WatchAnimeIdEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  WatchAnimeIdEpisodeIdRoute: WatchAnimeIdEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
